CC = gcc
OFLAGS = -o
extenC = .c

PROG = TP6_ma
VAR = TP6_freres

#On compile le main 
main:
	$(CC) $(PROG)$(extenC) $(OFLAGS) $(PROG)
	$(CC) $(VAR)$(extenC) $(OFLAGS) $(VAR)

#On clean les fichiers exécutables
clean:
	rm $(PROG) $(VAR)