CC = gcc
OFLAGS = -o
extenC = .c

PROG = recouvrant
VAR = fourchette

#On compile le main 
main:
	$(CC) recouvrant$(extenC) $(OFLAGS) $(PROG)
	$(CC) fourchette$(extenC) $(OFLAGS) $(VAR)

#On clean les fichiers exécutables
clean:
	rm $(PROG) $(VAR)